codeit-6th-part3-7team/7team-next-project

- .github/workflows/require-approval.yaml
1개 이상의 approve가 있어야 PR이 머지될 수 있도록 함
티켓 없음
1개 이상의 approve가 있어야 PR이 머지될 수 있도록 함
> :sparkles: [Add new action] 1개 이상의 approve가 있어야 PR이 머지될 수 있도록 함

- package-lock.json
- package.json
> 📚 install ui library

- tailwind.config.ts
테일윈드 커스텀 컬러 변수 설정
`tailwind.config.ts` 파일에 설정
> 🎨 tailwind custom-color

- .husky/pre-commit
- .vscode/settings.json
- package-lock.json
- package.json
- pages/api/axios.ts
- pages/wiki/[id].tsx
- src/apis/axios.ts
- src/types/ProfileResponse.d.ts
- axios 인스톨
- axios 인스턴스 작성
- api 호출 테스트를 위해 팀서버에 테스트용 데이터 생성
- profile 데이터 response body 타입 컴포넌트 작성
> 📝 api 호출함수 작성 및 테스트

- .eslintrc.js
- .husky/pre-commit
- .prettierrc.js
- package-lock.json
- package.json
- pages/signup.tsx
- src/styles/globals.css
- tsconfig.json
* react-hook-form, zod 라이브러리 설치
* 회원가입 필드 유효성 검사 기능 구현
> Feat/회원가입 폼 유효성 검사 기능 구현

- .vscode/settings.json
- pages/wiki/[id].tsx
https://2youlrang.atlassian.net/browse/KAN-22
주석 익스텐션 설치 및 적용 하였습니다!
> Feat/kan 22 setup api(Add extention and settings for annotation)

- .eslintrc.js
- .husky/pre-commit
- .prettierrc.js
- package.json
- pages/index.tsx
- tsconfig.json
> fix: crlf 오류, Parsing 오류 해결 및 lint 설정 변경

- .env
- .eslintrc.js
- .prettierrc.js
- package-lock.json
- package.json
- pages/_app.tsx
- pages/signup.tsx
- src/apis/axios.ts
- src/schema/signup.ts
- src/styles/globals.css
- src/styles/theme.ts
- src/types/type.ts
- tailwind.config.ts
* axios 설치
* mantine ui 적용
* 회원가입 기능 구현
* 회원가입 시 서버 응답에 따른 Notification 구현
ps. 얼른 로그인 만들겠습니다.. 조금만 기다려주세요..
> Feat/회원가입 기능 구현 및 mantine ui 적용

- pages/login.tsx
- pages/signup.tsx
- src/apis/axios.ts
- src/schema/userFormSchema.ts
- src/types/userFormData.ts
[Ticket]()
- 토큰 인증 인가 로직 구현
- 토큰 유효성에 따른 로그인 & 회원가입 페이지 접근시 랜딩 페이지로 리디렉션 구현
- 회원가입 시 로그인 페이지가 아닌 바로 랜딩 페이지로 이동하도록 바꿔봤는데 이상하다고 느껴지시면 다시 수정하겠습니다!
> Feat/토큰 인증 인가 구현

- .husky/pre-commit
- .vscode/settings.json
- next.config.mjs
- package-lock.json
- package.json
- pages/_app.tsx
- pages/index.tsx
- src/apis/axios.ts
- src/styles/globals.css
- src/styles/theme.ts
- tailwind.config.ts
https://2youlrang.atlassian.net/browse/KAN-48
- tailwind Custom option 추가
- next.config root 수정
- husky 커맨드 수정
- mantine 용 theme.ts 추가
- app에 provider 적용, notification 라이브러리 컴포넌트 추가
- global.css 수정
⭐️⭐️⭐️⭐️⭐️
1. **develop 브랜치로 이동 후** pull 받기
```
$ git pull
<or>
$ git pull origin develop
```
3. epic/page-name 에픽 브랜치에서 병합
```
$ git checkout epic/page-name
$ git merge develop
$ git push origin epic/page-name
```
4. 작업 중이던 브랜치가 있는 경우 feat/task-description 피처 브랜치에서 병합
```
$ git checkout feat/task-description
$ git merge develop
$ git push origin feat/task-description
```
> [KAN-48] tailwind axios setting for every companions

- next.config.mjs
- pages/_app.tsx
- pages/index.tsx
- pages/wiki/[id].tsx
- src/apis/authEditWiki.ts
- src/apis/axios.ts
- src/apis/checkWikiStatus.ts
- src/components/EditWikiAuthModal.tsx
- src/components/ProfileCard.tsx
- src/styles/theme.ts
- tailwind.config.ts
https://2youlrang.atlassian.net/browse/KAN-45
- 위키 수정상태 확인 로직 추가
- notification으로 오류처리
- 버튼 클릭이벤트 단계에서 위키 수정여부, 로그인여부 확인
- 승래님 작업하신 로그인기능 보면서 작업 했는데 머지 이후에 오류 생기면 수정작업 하겠습니다~!
> [KAN-39] 세션인증 구현

- .eslintrc.js
- .husky/pre-commit
- .prettierrc.js
- .vscode/settings.json
- package-lock.json
- package.json
- pages/_app.tsx
- pages/_document.tsx
- pages/wiki/[id].tsx
- src/apis/authEditWiki.ts
- src/apis/checkWikiStatus.ts
- src/components/EditWikiAuthModal.tsx
- src/components/ProfileCard.tsx
- src/styles/theme.ts
https://2youlrang.atlassian.net/browse/KAN-49
- husky pre-commit lint 설정 부분에 'run' 단어가 지워져있었네요...
- lint 오류 발생하는 부분들 다시 체크해서 수정 했습니다
> [KAN-49] lint 설정 오류 수정, lint오류 수정

- .env
- .eslintrc.js
- .gitignore
- gitignore에 .env 추가
- "jsx-a11y/label-has-associated-control" 규칙 추가 : 라벨이 연관된 인풋 요소 찾도록 함
> [setting] label 연관된 input 찾도록 규칙 지정

- .env
- .eslintrc.js
- .gitignore
- develop 머지 전 merge브랜치 생성 후 merge develop
> [merge] my wiki page 머지 확인

- .prettierrc.js
- pages/_document.tsx
- pages/wiki/[id].tsx
- pages/wikilist/index.tsx
- src/components/EditWikiAuthModal.tsx
- src/components/Pagination.tsx
- src/components/ProfileCard.tsx
- src/components/SearchFrom.tsx
- src/components/UserCard.tsx
주소에 id 값을 넣는게 아닌 name 값을 넣어 api를 불러오도록 했습니다. 
> [Refactor] wiki page

- .prettierrc.js
- pages/wiki/[id].tsx
- pages/wikilist/index.tsx
- src/apis/axios.ts
- src/components/Pagination.tsx
- src/components/UserCard.tsx
develop 브랜치에 병합하기 위헤 충돌 해결하는 브랜치입니다.
> [Merge] develop wiki list page

- pages/boards/[id]/index.tsx
- src/components/EditWikiAuthModal.tsx
https://2youlrang.atlassian.net/browse/KAN-11
- 디벨롭 브랜치 최신화하여 합쳤습니다~! 이전 머지PR에서 이부분을 놓쳐서 다시 올립니다~~
- 게시글 부분과 댓글 부분을 합치고, 변수명 살짝 바꿨습니다.
> [KAN-11] 게시글 상세페이지

- src/styles/globals.css
> fix: fix tailwind configuration in global css

- src/components/Board.tsx
> [KAN-12] 게시글 작성/수정페이지 삭제모달 버튼 색상 수정

- pages/wiki/[id]/index.tsx
develop 브랜치 병합 충돌 해결하는 PR 입니다. 
> [Merge] wiki list page

- src/components/UserCard.tsx
develop 브랜치와의 충돌 해결 후 약간의 코드 수정했습니다. 
> [Merge/Docs] wiki list end
